version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/performance_reviews
    depends_on:
      - mongodb
    networks:
      - performance-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - performance-network

networks:
  performance-network:
    driver: bridge

volumes:
  mongodb_data:
